import { Match } from '../types';
import type { SofaScoreData } from '../utils/sofascore-mapper';

/**
 * 5-team bracket example
 * - Round 1: 1 match (Team 1 vs Team 2)
 * - Round 2: 2 matches (Winner of R1 vs Team 3, Team 4 vs Team 5)
 * - Round 3: 1 match (Final)
 */
export const fiveTeamBracket: Match[] = [
  // Final - Round 3
  {
    id: 1,
    name: 'Final',
    nextMatchId: null,
    tournamentRoundText: '3',
    startTime: '2025-12-28',
    state: 'SCHEDULED',
    participants: [],
  },
  // Semi-finals - Round 2
  {
    id: 2,
    name: 'Semi-Final 1',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-27',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'team3',
        name: 'Team 3',
        isWinner: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Semi-Final 2',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-27',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'team4',
        name: 'Team 4',
        isWinner: false,
      },
      {
        id: 'team5',
        name: 'Team 5',
        isWinner: false,
      },
    ],
  },
  // Quarter-final - Round 1
  {
    id: 4,
    name: 'Quarter-Final',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'team1',
        name: 'Team 1',
        isWinner: false,
      },
      {
        id: 'team2',
        name: 'Team 2',
        isWinner: false,
      },
    ],
  },
];

/**
 * 6-team bracket with byes (using 'skip' mode)
 * - Round 1: 2 matches (Team 1 vs Team 2, Team 5 vs Team 6)
 * - Round 2: 2 matches (includes Team 3 and Team 4 with byes)
 * - Round 3: 1 match (Final)
 */
export const sixTeamBracketWithSkippedByes: Match[] = [
  // Final - Round 3
  {
    id: 1,
    name: 'Final',
    nextMatchId: null,
    tournamentRoundText: '3',
    startTime: '2025-12-28',
    state: 'SCHEDULED',
    participants: [],
  },
  // Semi-finals - Round 2
  {
    id: 2,
    name: 'Semi-Final 1',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-27',
    state: 'SCHEDULED',
    participants: [],
  },
  {
    id: 3,
    name: 'Semi-Final 2',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-27',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'team4',
        name: 'Team 4',
        isWinner: false,
      },
    ],
  },
  // Quarter-finals - Round 1 (bye matches with byeRenderMode: 'skip')
  {
    id: 4,
    name: 'Quarter-Final 1',
    nextMatchId: 3,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'SCHEDULED',
    byeRenderMode: 'skip',
    participants: [
      {
        id: 'team9',
        name: 'Team 9',
        isWinner: true,
        status: 'SCHEDULED',
      },
    ],
  },
  {
    id: 5,
    name: 'Quarter-Final 2',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'team1',
        name: 'Team 1',
        isWinner: true,
        status: 'PLAYED',
        resultText: '2',
      },
      {
        id: 'team2',
        name: 'Team 2',
        isWinner: false,
        status: 'PLAYED',
        resultText: '1',
      },
    ],
  },
  //   {
  //     id: 6,
  //     name: 'Quarter-Final 3',
  //     nextMatchId: 3,
  //     tournamentRoundText: '1',
  //     startTime: '2025-12-26',
  //     state: 'WALK_OVER',
  //     byeRenderMode: 'skip',
  //     participants: [
  //       {
  //         id: 'team4',
  //         name: 'Team 4',
  //         isWinner: true,
  //         status: 'WALK_OVER',
  //       },
  //     ],
  //   },
  {
    id: 7,
    name: 'Quarter-Final 4',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'team5',
        name: 'Team 5',
        isWinner: false,
        status: 'PLAYED',
        resultText: '0',
      },
      {
        id: 'team6',
        name: 'Team 6',
        isWinner: true,
        status: 'PLAYED',
        resultText: '3',
      },
    ],
  },
];

/**
 * 6-team bracket with visible bye indicators (using 'show-with-indicator' mode)
 * Same structure as above but byes are shown with "Bye to Round X" labels
 */
export const sixTeamBracketWithVisibleByes: Match[] = [
  // Final - Round 3
  {
    id: 1,
    name: 'Final',
    nextMatchId: null,
    tournamentRoundText: '3',
    startTime: '2025-12-28',
    state: 'SCHEDULED',
    participants: [],
  },
  // Semi-finals - Round 2
  {
    id: 2,
    name: 'Semi-Final 1',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-27',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'team3',
        name: 'Team 3',
        isWinner: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Semi-Final 2',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-27',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'team4',
        name: 'Team 4',
        isWinner: false,
      },
    ],
  },
  // Quarter-finals - Round 1 (bye matches with byeRenderMode: 'show-with-indicator')
  {
    id: 4,
    name: 'Quarter-Final 1',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'WALK_OVER',
    byeRenderMode: 'show-with-indicator',
    participants: [
      {
        id: 'team3',
        name: 'Team 3',
        isWinner: true,
        status: 'NO_PARTY',
      },
    ],
  },
  {
    id: 5,
    name: 'Quarter-Final 2',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'team1',
        name: 'Team 1',
        isWinner: true,
        status: 'PLAYED',
        resultText: '2',
      },
      {
        id: 'team2',
        name: 'Team 2',
        isWinner: false,
        status: 'PLAYED',
        resultText: '1',
      },
    ],
  },
  {
    id: 6,
    name: 'Quarter-Final 3',
    nextMatchId: 3,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'WALK_OVER',
    byeRenderMode: 'show-with-indicator',
    participants: [
      {
        id: 'team4',
        name: 'Team 4',
        isWinner: true,
        status: 'WALK_OVER',
      },
    ],
  },
  {
    id: 7,
    name: 'Quarter-Final 4',
    nextMatchId: 3,
    tournamentRoundText: '1',
    startTime: '2025-12-26',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'team5',
        name: 'Team 5',
        isWinner: false,
        status: 'PLAYED',
        resultText: '0',
      },
      {
        id: 'team6',
        name: 'Team 6',
        isWinner: true,
        status: 'PLAYED',
        resultText: '3',
      },
    ],
  },
];

/**
 * Mixed mode bracket - some byes are skipped, some are shown
 * Demonstrates per-match bye render mode overrides
 */
export const mixedModeBracket: Match[] = [
  // Final - Round 3
  {
    id: 1,
    name: 'Championship',
    nextMatchId: null,
    tournamentRoundText: '3',
    startTime: '2025-12-30',
    state: 'SCHEDULED',
    participants: [],
  },
  // Semi-finals - Round 2
  {
    id: 2,
    name: 'Semi-Final 1',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-29',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'teamA',
        name: 'Alpha Team',
        isWinner: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Semi-Final 2',
    nextMatchId: 1,
    tournamentRoundText: '2',
    startTime: '2025-12-29',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'teamB',
        name: 'Beta Squad',
        isWinner: false,
      },
    ],
  },
  // Quarter-finals - Round 1
  {
    id: 4,
    name: 'Quarter-Final 1',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'WALK_OVER',
    byeRenderMode: 'show-with-indicator', // Show this bye
    participants: [
      {
        id: 'teamA',
        name: 'Alpha Team',
        isWinner: true,
        status: 'WALK_OVER',
      },
    ],
  },
  {
    id: 5,
    name: 'Quarter-Final 2',
    nextMatchId: 2,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'teamC',
        name: 'Gamma Warriors',
        isWinner: true,
        status: 'PLAYED',
        resultText: '4',
      },
      {
        id: 'teamD',
        name: 'Delta Force',
        isWinner: false,
        status: 'PLAYED',
        resultText: '2',
      },
    ],
  },
  {
    id: 6,
    name: 'Quarter-Final 3',
    nextMatchId: 3,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'WALK_OVER',
    byeRenderMode: 'skip', // Skip this bye (won't render)
    participants: [
      {
        id: 'teamB',
        name: 'Beta Squad',
        isWinner: true,
        status: 'WALK_OVER',
      },
    ],
  },
  {
    id: 7,
    name: 'Quarter-Final 4',
    nextMatchId: 3,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'SCORE_DONE',
    participants: [
      {
        id: 'teamE',
        name: 'Epsilon Legends',
        isWinner: false,
        status: 'PLAYED',
        resultText: '1',
      },
      {
        id: 'teamF',
        name: 'Zeta Champions',
        isWinner: true,
        status: 'PLAYED',
        resultText: '5',
      },
    ],
  },
];

/**
 * Irregular bracket with teams starting at different rounds
 * - 1 team starts at semi-final
 * - 2 teams start at quarter-final
 * - 4 teams start at round 1
 */
export const irregularBracket: Match[] = [
  // Final
  {
    id: 1,
    name: 'Final',
    nextMatchId: null,
    tournamentRoundText: '4',
    startTime: '2025-12-31',
    state: 'SCHEDULED',
    participants: [],
  },
  // Semi-finals
  {
    id: 2,
    name: 'Semi-Final 1',
    nextMatchId: 1,
    tournamentRoundText: '3',
    startTime: '2025-12-30',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'seed1',
        name: 'Seed #1 (Starts in Semi)',
        isWinner: false,
      },
    ],
  },
  {
    id: 3,
    name: 'Semi-Final 2',
    nextMatchId: 1,
    tournamentRoundText: '3',
    startTime: '2025-12-30',
    state: 'SCHEDULED',
    participants: [],
  },
  // Quarter-finals
  {
    id: 4,
    name: 'Quarter-Final 1',
    nextMatchId: 2,
    tournamentRoundText: '2',
    startTime: '2025-12-29',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'seed2',
        name: 'Seed #2 (Starts in Quarter)',
        isWinner: false,
      },
    ],
  },
  {
    id: 5,
    name: 'Quarter-Final 2',
    nextMatchId: 3,
    tournamentRoundText: '2',
    startTime: '2025-12-29',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'seed3',
        name: 'Seed #3 (Starts in Quarter)',
        isWinner: false,
      },
    ],
  },
  // Round 1
  {
    id: 6,
    name: 'Round 1 - Match 1',
    nextMatchId: 4,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'seed4',
        name: 'Seed #4',
        isWinner: false,
      },
      {
        id: 'seed5',
        name: 'Seed #5',
        isWinner: false,
      },
    ],
  },
  {
    id: 7,
    name: 'Round 1 - Match 2',
    nextMatchId: 4,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'seed6',
        name: 'Seed #6',
        isWinner: false,
      },
      {
        id: 'seed7',
        name: 'Seed #7',
        isWinner: false,
      },
    ],
  },
  {
    id: 8,
    name: 'Round 1 - Match 3',
    nextMatchId: 5,
    tournamentRoundText: '1',
    startTime: '2025-12-28',
    state: 'SCHEDULED',
    participants: [
      {
        id: 'seed8',
        name: 'Seed #8',
        isWinner: false,
      },
      {
        id: 'seed9',
        name: 'Seed #9',
        isWinner: false,
      },
    ],
  },
];

export const sofascoredata: SofaScoreData = {
  cupTrees: [
    {
      id: 20949,
      name: 'Playoffs',
      tournament: {
        name: 'UEFA Champions League, Knockout stage',
        slug: 'uefa-champions-league-knockout-stage',
        category: {
          name: 'Europe',
          slug: 'europe',
          sport: {
            name: 'Football',
            slug: 'football',
            id: 1,
          },
          id: 1465,
          flag: 'europe',
          fieldTranslations: {
            nameTranslation: {
              ar: 'أوروبا',
              hi: 'यूरोप',
              bn: 'ইউরোপ',
            },
            shortNameTranslation: {},
          },
        },
        uniqueTournament: {
          name: 'UEFA Champions League',
          slug: 'uefa-champions-league',
          primaryColorHex: '#062b5c',
          secondaryColorHex: '#086aab',
          category: {
            name: 'Europe',
            slug: 'europe',
            sport: {
              name: 'Football',
              slug: 'football',
              id: 1,
            },
            id: 1465,
            flag: 'europe',
            fieldTranslations: {
              nameTranslation: {
                ar: 'أوروبا',
                hi: 'यूरोप',
                bn: 'ইউরোপ',
              },
              shortNameTranslation: {},
            },
          },
          userCount: 1170249,
          id: 7,
          displayInverseHomeAwayTeams: false,
          fieldTranslations: {
            nameTranslation: {
              ar: 'دوري أبطال أوروبا',
              hi: 'यूईएफए चैंपियंस लीग',
              bn: 'উয়েফা চ্যাম্পিয়ন্স লীগ',
            },
            shortNameTranslation: {},
          },
        },
        priority: 712,
        isLive: false,
        id: 23,
        fieldTranslations: {
          nameTranslation: {
            ar: 'دوري أبطال أوروبا',
            hi: 'यूईएफए चैंपियंस लीग',
            bn: 'উয়েফা চ্যাম্পিয়ন্স লীগ',
          },
          shortNameTranslation: {},
        },
      },
      currentRound: 4,
      rounds: [
        {
          order: 1,
          type: 8,
          description: '1/8',
          blocks: [
            {
              finished: true,
              matchesInRound: 2,
              order: 1,
              result: '3:2',
              homeTeamScore: '3',
              awayTeamScore: '2',
              participants: [
                {
                  team: {
                    name: 'Benfica',
                    slug: 'benfica',
                    shortName: 'Benfica',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 834582,
                    nameCode: 'SLB',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 3006,
                    teamColors: {
                      primary: '#cc0000',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'بنفيكا',
                        ru: 'Бенфика',
                        hi: 'बेनफिका',
                        bn: 'বেনফিকা',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  order: 1,
                  id: 2945443,
                },
                {
                  team: {
                    name: 'AFC Ajax',
                    slug: 'ajax',
                    shortName: 'Ajax',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 523346,
                    nameCode: 'AJA',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2953,
                    teamColors: {
                      primary: '#bb002b',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'أياكس أمستردام',
                        ru: 'Аякс',
                        hi: 'अजाक्स',
                        bn: 'আয়াক্স',
                      },
                      shortNameTranslation: {
                        ar: 'أياكس',
                      },
                    },
                  },
                  winner: false,
                  order: 2,
                  id: 2945444,
                },
              ],
              hasNextRoundLink: true,
              id: 1614403,
              events: [10012257, 10012264],
              blockId: 1,
              seriesStartDateTimestamp: 1645646400,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 2,
              result: '1:2',
              homeTeamScore: '1',
              awayTeamScore: '2',
              participants: [
                {
                  team: {
                    name: 'Inter',
                    slug: 'inter',
                    shortName: 'Inter',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 1799124,
                    nameCode: 'INT',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2697,
                    teamColors: {
                      primary: '#1a57cc',
                      secondary: '#000000',
                      text: '#000000',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'انتر',
                        ru: 'Интер',
                        hi: 'इंटर',
                        bn: 'ইন্টার',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  order: 1,
                  id: 2945445,
                },
                {
                  team: {
                    name: 'Liverpool',
                    slug: 'liverpool',
                    shortName: 'Liverpool',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3373767,
                    nameCode: 'LIV',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 44,
                    teamColors: {
                      primary: '#cc0000',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ليفربول',
                        ru: 'Ливерпуль',
                        hi: 'लिवरपूल',
                        bn: 'লিভারপুল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  order: 2,
                  id: 2945446,
                },
              ],
              hasNextRoundLink: true,
              id: 1614404,
              events: [10012269, 10012256],
              blockId: 2,
              seriesStartDateTimestamp: 1645041600,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 3,
              result: '4:1',
              homeTeamScore: '4',
              awayTeamScore: '1',
              participants: [
                {
                  team: {
                    name: 'Villarreal',
                    slug: 'villarreal',
                    shortName: 'Villarreal',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 434595,
                    nameCode: 'VIL',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2819,
                    teamColors: {
                      primary: '#ffff00',
                      secondary: '#013765',
                      text: '#013765',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'فياريال',
                        ru: 'Вильярреал',
                        hi: 'विल्लारियल',
                        bn: 'ভিলারিয়াল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  order: 1,
                  id: 2945448,
                },
                {
                  team: {
                    name: 'Juventus',
                    slug: 'juventus',
                    shortName: 'Juventus',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 1524895,
                    nameCode: 'JUV',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2687,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#000000',
                      text: '#000000',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'يوفنتوس',
                        ru: 'Ювентус',
                        hi: 'जुवेंटस',
                        bn: 'জুভেন্টাস',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  order: 2,
                  id: 2945447,
                },
              ],
              hasNextRoundLink: true,
              id: 1614405,
              events: [10012260, 10012263],
              blockId: 3,
              seriesStartDateTimestamp: 1645560000,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 4,
              result: '2:8',
              homeTeamScore: '2',
              awayTeamScore: '8',
              participants: [
                {
                  team: {
                    name: 'Red Bull Salzburg',
                    slug: 'red-bull-salzburg',
                    shortName: 'RB Salzburg',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 188764,
                    nameCode: 'RBS',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2046,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#ff0000',
                      text: '#ff0000',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ريد بول سالزبورغ',
                        ru: 'РБ Зальцбург',
                      },
                      shortNameTranslation: {
                        ar: 'إر بي سالزبورغ',
                        hi: 'आरबी साल्ज़बर्ग',
                        bn: 'আরবি সালজবার্গ',
                      },
                    },
                  },
                  winner: false,
                  order: 1,
                  id: 2945449,
                },
                {
                  team: {
                    name: 'FC Bayern München',
                    slug: 'fc-bayern-munchen',
                    shortName: 'Bayern',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2349328,
                    nameCode: 'FCB',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2672,
                    teamColors: {
                      primary: '#cf142f',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'إف سي بايرن ميونيخ',
                        ru: 'Бавария Мюнхен',
                      },
                      shortNameTranslation: {
                        ar: 'بايرن',
                        hi: 'बायर्न',
                        bn: 'বায়ার্ন',
                      },
                    },
                  },
                  winner: true,
                  order: 2,
                  id: 2945450,
                },
              ],
              hasNextRoundLink: true,
              id: 1614406,
              events: [10012259, 10012267],
              blockId: 4,
              seriesStartDateTimestamp: 1645041600,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 5,
              result: '5:0',
              homeTeamScore: '5',
              awayTeamScore: '0',
              participants: [
                {
                  team: {
                    name: 'Manchester City',
                    slug: 'manchester-city',
                    shortName: 'Man City',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3465531,
                    nameCode: 'MCI',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 17,
                    teamColors: {
                      primary: '#66ccff',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'مانشستر سيتي',
                        ru: 'Манчестер Сити',
                        hi: 'मेनचेस्टर सिटी ऍफ़सी',
                      },
                      shortNameTranslation: {
                        ar: 'مان سيتي',
                        hi: 'मैन सिटी',
                        bn: 'ম্যান সিটি',
                      },
                    },
                  },
                  winner: true,
                  order: 1,
                  id: 2945452,
                },
                {
                  team: {
                    name: 'Sporting CP',
                    slug: 'sporting',
                    shortName: 'Sporting',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 681530,
                    nameCode: 'SCP',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 3001,
                    teamColors: {
                      primary: '#009966',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'سبورتنج',
                        ru: 'Спортинг Лиссабон',
                        hi: 'स्पोर्टिंग',
                        bn: 'স্পোর্টিং',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  order: 2,
                  id: 2945451,
                },
              ],
              hasNextRoundLink: true,
              id: 1614407,
              events: [10012262, 10012266],
              blockId: 5,
              seriesStartDateTimestamp: 1644955200,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 6,
              result: '2:1',
              homeTeamScore: '2',
              awayTeamScore: '1',
              participants: [
                {
                  team: {
                    name: 'Atlético Madrid',
                    slug: 'atletico-madrid',
                    shortName: 'Atl. Madrid',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2014774,
                    nameCode: 'ATM',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2836,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#c40000',
                      text: '#c40000',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'أتلتيكو مدريد',
                        ru: 'Атлетико Мадрид',
                        hi: 'एटलेटिको मैड्रिड',
                      },
                      shortNameTranslation: {
                        ar: 'أتل. مدريد',
                        bn: 'এটিএল. মাদ্রিদ',
                      },
                    },
                  },
                  winner: true,
                  order: 1,
                  id: 2945453,
                },
                {
                  team: {
                    name: 'Manchester United',
                    slug: 'manchester-united',
                    shortName: 'Man Utd',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2986228,
                    nameCode: 'MUN',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 35,
                    teamColors: {
                      primary: '#ff0000',
                      secondary: '#373737',
                      text: '#373737',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'مانتشستر يونايتد',
                        ru: 'Манчестер Юнайтед',
                        hi: 'मेनचेस्टर यूनाइटेड ऍफ़सी',
                      },
                      shortNameTranslation: {
                        ar: 'مان يونايتد',
                        hi: 'मैन यूनाइटेड',
                        bn: 'ম্যান ইউনাইটেড',
                      },
                    },
                  },
                  winner: false,
                  order: 2,
                  id: 2945454,
                },
              ],
              hasNextRoundLink: true,
              id: 1614408,
              events: [10012254, 10012258],
              blockId: 6,
              seriesStartDateTimestamp: 1645646400,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 7,
              result: '4:1',
              homeTeamScore: '4',
              awayTeamScore: '1',
              participants: [
                {
                  team: {
                    name: 'Chelsea',
                    slug: 'chelsea',
                    shortName: 'Chelsea',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2762875,
                    nameCode: 'CHE',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 38,
                    teamColors: {
                      primary: '#0310a7',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'تشيلسي',
                        ru: 'Челси',
                        hi: 'चेल्सी',
                        bn: 'চেলসি',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  order: 1,
                  id: 2945455,
                },
                {
                  team: {
                    name: 'Lille',
                    slug: 'lille',
                    shortName: 'Lille',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 321389,
                    nameCode: 'LIL',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 1643,
                    teamColors: {
                      primary: '#df0000',
                      secondary: '#24216a',
                      text: '#24216a',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ليل',
                        ru: 'Лилль',
                        hi: 'लिली',
                        bn: 'লিল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  order: 2,
                  id: 2945456,
                },
              ],
              hasNextRoundLink: true,
              id: 1614409,
              events: [10012255, 10012261],
              blockId: 7,
              seriesStartDateTimestamp: 1645560000,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 8,
              result: '2:3',
              homeTeamScore: '2',
              awayTeamScore: '3',
              participants: [
                {
                  team: {
                    name: 'Paris Saint-Germain',
                    slug: 'paris-saint-germain',
                    shortName: 'PSG',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2752527,
                    nameCode: 'PSG',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 1644,
                    teamColors: {
                      primary: '#000066',
                      secondary: '#ff1541',
                      text: '#ff1541',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'باريس سان جيرمان',
                        ru: 'Пари Сен-Жермен',
                        hi: 'पेरिस सेंट-जर्मेन',
                      },
                      shortNameTranslation: {
                        hi: 'पीएसजी',
                        bn: 'পিএসজি',
                      },
                    },
                  },
                  winner: false,
                  order: 1,
                  id: 2945457,
                },
                {
                  team: {
                    name: 'Real Madrid',
                    slug: 'real-madrid',
                    shortName: 'Real Madrid',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 6350889,
                    nameCode: 'RMA',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2829,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#004996',
                      text: '#004996',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ريال مدريد',
                        ru: 'Реал Мадрид',
                        hi: 'रियल मैड्रिड',
                        bn: 'রিয়াল মাদ্রিদ',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  order: 2,
                  id: 2945458,
                },
              ],
              hasNextRoundLink: true,
              id: 1614410,
              events: [10012265, 10012268],
              blockId: 8,
              seriesStartDateTimestamp: 1644955200,
              automaticProgression: false,
            },
          ],
          id: 92336,
        },
        {
          order: 2,
          type: 4,
          description: 'Quarterfinals',
          blocks: [
            {
              finished: true,
              matchesInRound: 2,
              order: 1,
              result: '4:6',
              homeTeamScore: '4',
              awayTeamScore: '6',
              participants: [
                {
                  team: {
                    name: 'Benfica',
                    slug: 'benfica',
                    shortName: 'Benfica',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 834582,
                    nameCode: 'SLB',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 3006,
                    teamColors: {
                      primary: '#cc0000',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'بنفيكا',
                        ru: 'Бенфика',
                        hi: 'बेनफिका',
                        bn: 'বেনফিকা',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  sourceBlockId: 1,
                  order: 1,
                  id: 2986248,
                },
                {
                  team: {
                    name: 'Liverpool',
                    slug: 'liverpool',
                    shortName: 'Liverpool',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3373767,
                    nameCode: 'LIV',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 44,
                    teamColors: {
                      primary: '#cc0000',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ليفربول',
                        ru: 'Ливерпуль',
                        hi: 'लिवरपूल',
                        bn: 'লিভারপুল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  sourceBlockId: 2,
                  order: 2,
                  id: 2986249,
                },
              ],
              hasNextRoundLink: true,
              eventInProgress: false,
              id: 1629018,
              events: [10200680, 10200684],
              blockId: 1,
              seriesStartDateTimestamp: 1649185200,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 2,
              result: '2:1',
              homeTeamScore: '2',
              awayTeamScore: '1',
              participants: [
                {
                  team: {
                    name: 'Villarreal',
                    slug: 'villarreal',
                    shortName: 'Villarreal',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 434595,
                    nameCode: 'VIL',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2819,
                    teamColors: {
                      primary: '#ffff00',
                      secondary: '#013765',
                      text: '#013765',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'فياريال',
                        ru: 'Вильярреал',
                        hi: 'विल्लारियल',
                        bn: 'ভিলারিয়াল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  sourceBlockId: 3,
                  order: 1,
                  id: 2986250,
                },
                {
                  team: {
                    name: 'FC Bayern München',
                    slug: 'fc-bayern-munchen',
                    shortName: 'Bayern',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2349328,
                    nameCode: 'FCB',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2672,
                    teamColors: {
                      primary: '#cf142f',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'إف سي بايرن ميونيخ',
                        ru: 'Бавария Мюнхен',
                      },
                      shortNameTranslation: {
                        ar: 'بايرن',
                        hi: 'बायर्न',
                        bn: 'বায়ার্ন',
                      },
                    },
                  },
                  winner: false,
                  sourceBlockId: 4,
                  order: 2,
                  id: 2986251,
                },
              ],
              hasNextRoundLink: true,
              eventInProgress: false,
              id: 1629019,
              events: [10200673, 10200674],
              blockId: 2,
              seriesStartDateTimestamp: 1649271600,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 3,
              result: '1:0',
              homeTeamScore: '1',
              awayTeamScore: '0',
              participants: [
                {
                  team: {
                    name: 'Manchester City',
                    slug: 'manchester-city',
                    shortName: 'Man City',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3465531,
                    nameCode: 'MCI',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 17,
                    teamColors: {
                      primary: '#66ccff',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'مانشستر سيتي',
                        ru: 'Манчестер Сити',
                        hi: 'मेनचेस्टर सिटी ऍफ़सी',
                      },
                      shortNameTranslation: {
                        ar: 'مان سيتي',
                        hi: 'मैन सिटी',
                        bn: 'ম্যান সিটি',
                      },
                    },
                  },
                  winner: true,
                  sourceBlockId: 5,
                  order: 1,
                  id: 2986252,
                },
                {
                  team: {
                    name: 'Atlético Madrid',
                    slug: 'atletico-madrid',
                    shortName: 'Atl. Madrid',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2014774,
                    nameCode: 'ATM',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2836,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#c40000',
                      text: '#c40000',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'أتلتيكو مدريد',
                        ru: 'Атлетико Мадрид',
                        hi: 'एटलेटिको मैड्रिड',
                      },
                      shortNameTranslation: {
                        ar: 'أتل. مدريد',
                        bn: 'এটিএল. মাদ্রিদ',
                      },
                    },
                  },
                  winner: false,
                  sourceBlockId: 6,
                  order: 2,
                  id: 2986253,
                },
              ],
              hasNextRoundLink: true,
              eventInProgress: false,
              id: 1629020,
              events: [10200679, 10200678],
              blockId: 3,
              seriesStartDateTimestamp: 1649185200,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 4,
              result: 'away won',
              homeTeamScore: '4',
              awayTeamScore: '5',
              participants: [
                {
                  team: {
                    name: 'Chelsea',
                    slug: 'chelsea',
                    shortName: 'Chelsea',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 2762875,
                    nameCode: 'CHE',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 38,
                    teamColors: {
                      primary: '#0310a7',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'تشيلسي',
                        ru: 'Челси',
                        hi: 'चेल्सी',
                        bn: 'চেলসি',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  sourceBlockId: 7,
                  order: 1,
                  id: 2986254,
                },
                {
                  team: {
                    name: 'Real Madrid',
                    slug: 'real-madrid',
                    shortName: 'Real Madrid',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 6350889,
                    nameCode: 'RMA',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2829,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#004996',
                      text: '#004996',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ريال مدريد',
                        ru: 'Реал Мадрид',
                        hi: 'रियल मैड्रिड',
                        bn: 'রিয়াল মাদ্রিদ',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  sourceBlockId: 8,
                  order: 2,
                  id: 2986255,
                },
              ],
              hasNextRoundLink: true,
              eventInProgress: false,
              id: 1629021,
              events: [10200677, 10200675],
              blockId: 4,
              seriesStartDateTimestamp: 1649271600,
              automaticProgression: false,
            },
          ],
          id: 92337,
        },
        {
          order: 3,
          type: 2,
          description: 'Semifinals',
          blocks: [
            {
              finished: true,
              matchesInRound: 2,
              order: 1,
              result: '5:2',
              homeTeamScore: '5',
              awayTeamScore: '2',
              participants: [
                {
                  team: {
                    name: 'Liverpool',
                    slug: 'liverpool',
                    shortName: 'Liverpool',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3373767,
                    nameCode: 'LIV',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 44,
                    teamColors: {
                      primary: '#cc0000',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ليفربول',
                        ru: 'Ливерпуль',
                        hi: 'लिवरपूल',
                        bn: 'লিভারপুল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  sourceBlockId: 1,
                  order: 1,
                  id: 2996308,
                },
                {
                  team: {
                    name: 'Villarreal',
                    slug: 'villarreal',
                    shortName: 'Villarreal',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 434595,
                    nameCode: 'VIL',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2819,
                    teamColors: {
                      primary: '#ffff00',
                      secondary: '#013765',
                      text: '#013765',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'فياريال',
                        ru: 'Вильярреал',
                        hi: 'विल्लारियल',
                        bn: 'ভিলারিয়াল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  sourceBlockId: 2,
                  order: 2,
                  id: 2996315,
                },
              ],
              hasNextRoundLink: true,
              eventInProgress: false,
              id: 1614415,
              events: [10253768, 10253769],
              blockId: 1,
              seriesStartDateTimestamp: 1651086000,
              automaticProgression: false,
            },
            {
              finished: true,
              matchesInRound: 2,
              order: 2,
              result: 'away won',
              homeTeamScore: '5',
              awayTeamScore: '6',
              participants: [
                {
                  team: {
                    name: 'Manchester City',
                    slug: 'manchester-city',
                    shortName: 'Man City',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3465531,
                    nameCode: 'MCI',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 17,
                    teamColors: {
                      primary: '#66ccff',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'مانشستر سيتي',
                        ru: 'Манчестер Сити',
                        hi: 'मेनचेस्टर सिटी ऍफ़सी',
                      },
                      shortNameTranslation: {
                        ar: 'مان سيتي',
                        hi: 'मैन सिटी',
                        bn: 'ম্যান সিটি',
                      },
                    },
                  },
                  winner: false,
                  sourceBlockId: 3,
                  order: 1,
                  id: 2996310,
                },
                {
                  team: {
                    name: 'Real Madrid',
                    slug: 'real-madrid',
                    shortName: 'Real Madrid',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 6350889,
                    nameCode: 'RMA',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2829,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#004996',
                      text: '#004996',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ريال مدريد',
                        ru: 'Реал Мадрид',
                        hi: 'रियल मैड्रिड',
                        bn: 'রিয়াল মাদ্রিদ',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  sourceBlockId: 4,
                  order: 2,
                  id: 2996316,
                },
              ],
              hasNextRoundLink: true,
              eventInProgress: false,
              id: 1614416,
              events: [10253774, 10253773],
              blockId: 2,
              seriesStartDateTimestamp: 1650999600,
              automaticProgression: false,
            },
          ],
          id: 92338,
        },
        {
          order: 4,
          type: 1,
          description: 'Final',
          blocks: [
            {
              finished: true,
              matchesInRound: 1,
              order: 1,
              result: 'away won',
              homeTeamScore: '0',
              awayTeamScore: '1',
              participants: [
                {
                  team: {
                    name: 'Liverpool',
                    slug: 'liverpool',
                    shortName: 'Liverpool',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 3373767,
                    nameCode: 'LIV',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 44,
                    teamColors: {
                      primary: '#cc0000',
                      secondary: '#ffffff',
                      text: '#ffffff',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ليفربول',
                        ru: 'Ливерпуль',
                        hi: 'लिवरपूल',
                        bn: 'লিভারপুল',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: false,
                  sourceBlockId: 1,
                  order: 1,
                  id: 3022497,
                },
                {
                  team: {
                    name: 'Real Madrid',
                    slug: 'real-madrid',
                    shortName: 'Real Madrid',
                    gender: 'M',
                    sport: {
                      name: 'Football',
                      slug: 'football',
                      id: 1,
                    },
                    userCount: 6350889,
                    nameCode: 'RMA',
                    disabled: false,
                    national: false,
                    type: 0,
                    id: 2829,
                    teamColors: {
                      primary: '#ffffff',
                      secondary: '#004996',
                      text: '#004996',
                    },
                    fieldTranslations: {
                      nameTranslation: {
                        ar: 'ريال مدريد',
                        ru: 'Реал Мадрид',
                        hi: 'रियल मैड्रिड',
                        bn: 'রিয়াল মাদ্রিদ',
                      },
                      shortNameTranslation: {},
                    },
                  },
                  winner: true,
                  sourceBlockId: 2,
                  order: 2,
                  id: 3022500,
                },
              ],
              hasNextRoundLink: false,
              eventInProgress: false,
              id: 1614417,
              events: [10292810],
              blockId: 1,
              seriesStartDateTimestamp: 1653764400,
              automaticProgression: false,
            },
          ],
          id: 92339,
        },
      ],
      type: 1,
      showSingleParticipantByeBlocks: false,
      hideRoundsWithoutParticipants: false,
    },
  ],
};
